# Note this file is using variables and secrets added in github repo itself in setting (assigned manually)
# secrets cant be printed in actions but it can be passed to runner and then used/printed there. but variables can be printed anywhere as its not confidential
# 4 types
name: All about variables,secrets and environment

on: workflow_dispatch

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Display general variable name
        run: |
          echo "general repo variable value is: ${{ vars.GNRLVAR }}"

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Display general secret name
        run: |
          echo "general repo secret value is: ${{ secrets.GNRLSEC }}"

  test3:
    runs-on: ubuntu-latest
    environment: TESTENV
    steps:
      - name: Display environment variable name
        run: |
          echo "mentioned environment variable value is: ${{ vars.ENVVAR }}"

  test4:
    runs-on: ubuntu-latest
    environment: TESTENV
    steps:
      - name: Display environment secret name
        run: |
          echo "mentioned environment secret value is: ${{ secrets.ENVSEC }}"

#   test5:
#     runs-on: ubuntu-latest
#     environment: inputs
#     env:
#     steps:
#         -name: using environemtn variables in runner from created environent
