name: Output event Details if any issues created on Repository
on:
    issues:
      types: opened   # i modified it to trigger this workflow only when issue is opened and not closed
jobs:
  issuesinfo:
    runs-on: ubuntu-latest
    steps:
      - name: Output github Context
        run: echo "${{toJSON(github)}}"