# download generated reports to local after job is completed..
name: Download Report to Local 
on: workflow_dispatch                         
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm ci                
      - name: Run Build
        run: npm run build
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
            name: TestReport
            path: dist

  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
        # - name: Get Code
        #   uses: actions/checkout@v4 

        # - name: download job artifacts
        #   uses: actions/download-artifact@v4
        #   with:
        #       name: TestReport
        #       path: Reports   --> here its still downloaded in github storage or runner, not to local,,
              
        - name: download  
          run: |
            echo "Downloading the Playwright report..."
            gh auth login --with-token <<< "$GITHUB_TOKEN"
            gh run download --name TestReport --dir ./Reports

