# download generated reports to local after job is completed..
name: Download Report to Local 
on: workflow_dispatch                         
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm ci                
      - name: Run Build
        run: npm run build
      - name: Upload artefatcs
        uses: actions/upload-artifact@v4
        with:
            name: TestReport
            path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: download job artifacts
          uses: actions/download-artifact@v4
          with:
              name: TestReport
              path: Reports            

