# below two points might take priority over all below code poitns
# main important: general secrets will store in users account thats unique for every user so that will be picked from user specific
# but if i create a environment and add secrets / env variables inside that then its only used by repo owners in private repo and public repo anyone can use those environments added in that repo settings..
# so add a dropdown to asign env variables in github actions and use them in code for running purpose , hardcode not required values..

name: Environment variables Setup & Secrets
# Note: storing credentials in workflow file is not ideal , this is just an exercise
on: workflow_dispatch
env:                        # workflow level env variables ( can be used for all jobs)
    USERNAME: John Doe
    PASSWORD: ${{ secrets.PASSWORD }}  # im getting passwords from secrets stored in github website ( see notes to learn how to save a secret variable in github website ) 
jobs:
    test: 
        env:                # job level env variables ( only for this job)
            EXCELWORKBOOKNAME: myExcel1
            EXCELSHEETNAME: mySheet1
        runs-on: ubuntu-latest
        steps:                
          - name: Display general env variable name
            run: |
              echo "Username is: ${{ env.USERNAME }}"
              echo "ExcelWorkbookName is: ${{ env.EXCELWORKBOOKNAME }}"
              echo "Password is: ${{ secrets.PASSWORD }}"

# Note : secret values cannot be printed , github actions hides the access of secrets from env context
# we can get env object name by using env context

    testenv:
        environment: demoenv
        runs-on: ubuntu-latest
        steps:                
          - name: Display environemnt specific secret password
            run: |
              echo "Environment specific secret pwd is: ${{ secrets.PASSWORD }}"

# Note: if i run some code and those code uses same environment then they also get the same values assign by manually in eorkflow file like first job , addign through a environment in repo settings.
# i created demoenv in github desktop and defined different username
# here in both jobs password secret is present , but in second job here it pics username defined in "demoenv" environment as specified in job ( it wont pick general Username secret which is accessible for all jobs) 
# this is usefull when we need top run same job with different credentials for acceessing different environemnts
# Note : for an created enviroment we can  define both env specific environment variables + secrets as well
# in reality create an environment like stage, test, production in github repo --> settings --> environments tab and use them in workflow file ( add a dropdown to select which environment testing is going on ,based on that read env variables and perform testing)
# if i create some env & its variables and use that env in workflow , the related codes will use that env variables