name: Environment variables Setup
# Note: storing credentials in workflow file is not ideal , this is just an exercise
on: workflow_dispatch
env:                        # workflow level env variables ( can be used for all jobs)
    USERNAME: John Doe
    PASSWORD: johndoe123
jobs:
    test: 
        env:                # job level env variables ( only for this job)
            EXCELWORKBOOKNAME: myExcel1
            EXCELSHEETNAME: mySheet1
        runs-on: ubuntu-latest
        steps:                
          - name: Display env variable name
            run: |
              echo "Username is: ${{ env.USERNAME }}"
              echo "ExcelWorkbookName is: ${{ env.EXCELWORKBOOKNAME }}"   

# we can get env object name by using env context