name: Environment variables Setup & Secrets
# Note: storing credentials in workflow file is not ideal , this is just an exercise
on: workflow_dispatch
env:                        # workflow level env variables ( can be used for all jobs)
    USERNAME: John Doe
    PASSWORD: ${{ secrets.PASSWORD }}  # im getting passwords from secrets stored in github website ( see notes to learn how to save a secret variable in github website ) 
jobs:
    test: 
        env:                # job level env variables ( only for this job)
            EXCELWORKBOOKNAME: myExcel1
            EXCELSHEETNAME: mySheet1
        runs-on: ubuntu-latest
        steps:                
          - name: Display general env variable name
            run: |
              echo "Username is: ${{ env.USERNAME }}"
              echo "ExcelWorkbookName is: ${{ env.EXCELWORKBOOKNAME }}"
              echo "Password is: ${{ secrets.PASSWORD }}"

# Note : secret values cannot be printed , github actions hides the access of secrets from env context
# we can get env object name by using env context

    testenv:
        environment: demoenv
        runs-on: ubuntu-latest
        steps:                
          - name: Display environemnt specific secret password
            run: |
              echo "Environment specific secret pwd is: ${{ secrets.PASSWORD }}"

# i created demoenv in github desktop and defined different username
# here in both jobs password secret is present , but in second job here it pics username defined in "demoenv" environment as specified in job ( it wont pick general Username secret which is accessible for all jobs) 
# this is usefull when we need top run same job with different credentials for acceessing different environemnts
# Note : for an created enviroment we can  define both env specific environment variables + secrets as well