name: Job Artefact
on: workflow_dispatch                         
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm ci                
      - name: Run Build
        run: npm run build
      - name: Upload artefatcs
        uses: actions/upload-artifact@v4
        with:
            name: dist-files
            path: |
                dist
                package.json    

# above im making 1 folder(dist) and 1 file(package.json) as one job artefact
# Refer https://github.com/actions/upload-artifact for all configaration info ( include some file , exclude some file etc..)
