name: Docker Container
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest  # now this runner will just host the image , jobs will run in container
    container:              # define container here with its image and version
        image: node:16  
      # env: if docker image needs its env it will be mentioned here & goto docker website, search node and check which env node image needs Eg: https://hub.docker.com/_/node
    steps:
      - name: Get Code
        uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm ci                
      - name: Run tests
        run: npm test 

# now open workflow and cehck details , it will initialise containers and run all jobs there