name: Print Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: print greeting
        run: echo "Hello, I'm Learning GitHub Actions"
      - name: print goodbye
        run: echo "Good Bye!"
# run is used to run a simple shell command in server (runner)