# since for build i already have a workflow/job , by mentioning its path i can call that workflow here for deploying
name: Reusable Workflow Part 2
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run test
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run build
        run: npm run builder
      - name: Upload build report only if run build step fails
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    uses: ./.github/workflows/fourteenth_workflow_reusable_workflow_part1.yml

  reporting:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Say us if any one or more previous job is failed
        run: echo " Report Uploaded!..."
