# combining two or more workflows and making it as one
# i.e using other workflow in this workflow Eg: if build is seperate existing workflow, if im creating build + test workflow i can use existing test workflow here while making new build+test workflow

name: Reusable Workflow Part 1
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm ci                
      - name: Run Build
        run: npm run build
      - name: Deploy Code
        run: echo "Deploying..."

# if i use workflow_call event that means this workflow can be called in other workflow ( i can use [ workflow_dispatch, push, workflow_call ] like this too)
