#since on: push event triggers workflow for every push om any branch of that main branch, we can configure it to trigger on certain conditions only ( Eg: trigger workflow only when commit is pushed to main branch)
name: Events Configaration
on:
  pull_request:             # first event to trigger a workflow and its configaration
    types:
      - opened
    branches:
        - main              # trigger workflow if PR raised to main branch only 
  # branches-ignore:
  #    - DemoBranch        ignore any PR to my demobranch ( not from demo branch to main) ( branches and branches ignore cant be used together?)
  workflow_dispatch:        # second event to trigger workflow (manual)

  # turning off below auto push run trigger off for learning other things ( remove srating 7 #s below to make it active)
  # push:                     # second event to trigger workflow ( filter: only if committed(pushed) to main branch)
  #   branches:
  #       - main
  #   #   - 'dev-*' --> any branch starts with dev word    (Regex)
  #   #   - 'feat/**' --> all branch start with feat/ and alternative / s in branch name eg: feat/new , feat/new/button etc...
  #   paths-ignore:
  #       - '.github/workflow/*' # do not trigger workflow if any changes done in workflow folder , if 'paths' is used then workflow will be triggered only if file changes done in that file

jobs:
  event_config_filters:
    runs-on: ubuntu-latest
    steps:
      - name: Event config and filters
        run: echo "Configuring events and usage of filters"

# Now switch to demobranch and do some minor changes and raise a PR to trigger this workflow.
# workflow run can be skipped by adding a specific keyword in commit mesage , refer notes for more info