# this action is used to cehck the syntax of python code , if any syntax error workflow will fail
# find this action info in github marketplace --> https://github.com/marketplace/actions/python-syntax-checker
# this workflow is working fine..

name: Python Syntax Checker

on: workflow_dispatch

jobs:
  syntaxCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Navigate to python Directory 
        run: cd eg_python

      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
            
        
# we can pass arguments to any action using with: keyword , eg checkout action comes with some configaration too , we can mention them using with: keyword  --> refer https://github.com/actions/checkout  