name: Test Workflow
on: push    # this test code containing workflow will be triggered after each push to the repository
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: 
# to define a action in steps we need to use "uses" keyword