name: Test Workflow
on: push                          # this test code containing workflow will be triggered after each push to the repository
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4 # to define a action in steps we need to use "uses" keyword , here "checkout" action is used to provide code from current repo to runner/server
      - name: Install Node JS     # since ubuntu latest runner already has default node js i dont need this step , but still using just for practice by providing some node version
        uses: actions/setup-node@v4 # using setup-node action to install '18' th version of node in runner ( if runner version of node is outdated then this is usefull)
        with:
          node-version: 21
      - name: Install Dependencies
        run: npm ci                # command to install project defined dependencies ( in this repo react is dependency) ( even though if react is not installed in local system , it will be installed in runner/ github server)
      - name: Run tests
        run: npm test              # command as defined in package.json file
  deploy:                          # second job to build the code
    needs: test                    # this "needs" keyword used to run test in series , only if "test" job is passed then only this job will run , else by default all jobs run in parallel
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4 
      - name: Install Node JS     
        uses: actions/setup-node@v4 
        with:
          node-version: 21
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build        # this command is part of package.json
      - name: Deploy
        run: echo "Deploying...."

# this workflow will run after each push to the repo ( as its configured for each push) --> first job
# the second job will build the code