name: Controlling Jobs workflow
on: workflow_dispatch                         
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm ci                
      - name: Run build          
        run: npm run build
      - name: Upload build report only if run build step fails     
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

# below is a conditional job  ( make sure it runs in series)
# this job only run if failure() is true. that is if any previous job (  here its build job )is failed then only reporting job will run
  reporting:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Say us if any one or more previous job is failed 
        run: echo " Report Uploaded!..."
