name: Matrix Demo
on: workflow_dispatch
jobs:
    build:
        continue-on-error: true   
        strategy:
            matrix:
                node-version: [12,14,16]
                operating-system: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Node JS    
              uses: actions/setup-node@v4 
              with:
                node-version: ${{matrix.node-version}}
            - name: Install Dependencies
              run: npm ci                
            - name: Run Build
              run: npm run build 

# here i have 6 combinations , some will fail so other combinations it might not run  ( so i added continue-on error : true , so even if first combination fails other combination jobs will run)
# Note: continue-on-error can be added at job level too , so series of job will continue even if previous job fails
# matrix key can be any , but it should be mapped corrrectly
# usefull top run codes in multiple versions
# Note: all combinations might not pass as each verison , operationg system might have some limitations or might not have proper dependencies