name: Matrix Demo
on: workflow_dispatch
jobs:
    build:
        strategy:
            matrix:
                node-version: [12,14,16]
                operating-system: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Node JS    
              uses: actions/setup-node@v4 
              with:
                node-version: ${{matrix.node-version}}
            - name: Install Dependencies
              run: npm ci                
            - name: Run Build
              run: npm run build 

# matrix key can be any , but it should be mapped corrrectly
# usefull top run codes in multiple versions