name: Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output github Context
        run: echo "${{toJSON(github)}}"     # we are accessing data of "github" context and printing it with the help of expression
# github actions will crete/provide many contexts while running a workflow or a job , we can access them using contextss
